# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ben < Formula
  desc "ben — benchmark and registry tooling for hop.top"
  homepage "https://github.com/hop-top/ben"
  version "0.2.0-alpha.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hop-top/ben/releases/download/ben/v0.2.0-alpha.1/ben_0.2.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "1bc9af32b620712c731441005a1a4da0f48d670bd545e3ec2c00a8a325e3a47d"

      define_method(:install) do
        bin.install "ben"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hop-top/ben/releases/download/ben/v0.2.0-alpha.1/ben_0.2.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "75bb871c3137a221fc679529ee64b8490db763418402d49e3d7eb89e8d2086e6"

      define_method(:install) do
        bin.install "ben"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hop-top/ben/releases/download/ben/v0.2.0-alpha.1/ben_0.2.0-alpha.1_linux_amd64.tar.gz"
      sha256 "b42d928015f90233a134cce3b89d1b2fd90efcccaeb67147af2b46ced842f80e"
      define_method(:install) do
        bin.install "ben"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hop-top/ben/releases/download/ben/v0.2.0-alpha.1/ben_0.2.0-alpha.1_linux_arm64.tar.gz"
      sha256 "73c7e70c8e0d40dae1a610cf3c0df5a58def9819a437b0c7cf06edc028c53d14"
      define_method(:install) do
        bin.install "ben"
      end
    end
  end

  test do
    system "#{bin}/ben", "--version"
  end
end
