# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Usp < Formula
  desc "Universal Sessions Protocol — find any coding session across any AI assistant."
  homepage "https://github.com/hop-top/usp"
  version "0.1.0-alpha.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hop-top/usp/releases/download/usp/v0.1.0-alpha.1/usp_0.1.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "5f41b7afbf2e764e7539f7efb15767992abe4f85f212efeff3361526b415560d"

      define_method(:install) do
        bin.install "usp"
        bin.install "usp-ctxt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hop-top/usp/releases/download/usp/v0.1.0-alpha.1/usp_0.1.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "d9059fb7d8b7fcdeb40b73d8bbc0f74f3ff595e0c2fa9df4e19d3fa10f3281ac"

      define_method(:install) do
        bin.install "usp"
        bin.install "usp-ctxt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hop-top/usp/releases/download/usp/v0.1.0-alpha.1/usp_0.1.0-alpha.1_linux_amd64.tar.gz"
      sha256 "4b579edc8355a47a85b406bbf4fe755419224cb19f777b6ca2964cf8b0484946"
      define_method(:install) do
        bin.install "usp"
        bin.install "usp-ctxt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hop-top/usp/releases/download/usp/v0.1.0-alpha.1/usp_0.1.0-alpha.1_linux_arm64.tar.gz"
      sha256 "80b7cdfd84a0b7e6e3ab843e408ed60401e0706aeffd66afad10bddcd0178cd3"
      define_method(:install) do
        bin.install "usp"
        bin.install "usp-ctxt"
      end
    end
  end

  test do
    system "#{bin}/usp", "--version"
  end
end
