# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Usp < Formula
  desc "Universal Sessions Protocol — find any coding session across any AI assistant."
  homepage "https://github.com/hop-top/usp"
  version "0.1.0-alpha.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hop-top/usp/releases/download/usp/v0.1.0-alpha.1/usp_0.1.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "5c89c0ae6a2ba60543a1da4eab2295add0ccb29e598dddca501acad8e0542ec1"

      define_method(:install) do
        bin.install "usp"
        bin.install "usp-ctxt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hop-top/usp/releases/download/usp/v0.1.0-alpha.1/usp_0.1.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "fbd2cabe96a81542f83268326d5148a6abbb49361b920b3f936ed195df59cb98"

      define_method(:install) do
        bin.install "usp"
        bin.install "usp-ctxt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hop-top/usp/releases/download/usp/v0.1.0-alpha.1/usp_0.1.0-alpha.1_linux_amd64.tar.gz"
      sha256 "173267571996e7ad7ecac69ce6087a9de013478ad34938a87b12914323c8cc86"
      define_method(:install) do
        bin.install "usp"
        bin.install "usp-ctxt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hop-top/usp/releases/download/usp/v0.1.0-alpha.1/usp_0.1.0-alpha.1_linux_arm64.tar.gz"
      sha256 "37be5aefc42b8fb9bdf273bfced68eac203a6638ce36487b1578fc7804ce1f99"
      define_method(:install) do
        bin.install "usp"
        bin.install "usp-ctxt"
      end
    end
  end

  test do
    system "#{bin}/usp", "--version"
  end
end
